---
ID: "1100c2f0-22b0-4856-bcba-d3637563069c"
Parent: "d1a71a1b-1731-4f0a-b5fb-1e0c72647cd6"
Template: "d1a71a1b-1731-4f0a-b5fb-1e0c72647cd6"
Path: /sitecore/templates/Project/Builderz/Base Templates/_PageData/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210602T043458Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
