---
ID: "4ca2b28d-90e4-40bc-8342-d5976a928aad"
Parent: "0abd47d4-ba34-48a9-85a3-e8ecee90799e"
Template: "0abd47d4-ba34-48a9-85a3-e8ecee90799e"
Path: /sitecore/templates/Project/Builderz/Page Templates/Book Landing Page/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {C77CBF36-E660-4C1A-AB94-85F172CA180A}
    {0ABD47D4-BA34-48A9-85A3-E8ECEE90799E}
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{83C3EED6-3049-4026-BD16-A59310F1DD1C}">
        <r
          id="{1E445CBB-C0CC-47F5-9F19-2C19D3C1537D}"
          ph="main"
          uid="{56B482DE-EDD8-429E-AAF8-2752E3C0280A}" />
        <r
          id="{E54F91CA-4A1E-4A24-805D-5070F1D2043F}"
          ph="main"
          uid="{BE7E0547-07A8-4D38-94FD-305E840448B5}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190511T050151Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
