---
ID: "ebe5eb8a-446d-4354-b320-ad3f4b9e919f"
Parent: "89fbb931-d737-4468-926d-e14e1a11ee2a"
Template: "89fbb931-d737-4468-926d-e14e1a11ee2a"
Path: /sitecore/templates/Project/Builderz/Data Templates/Slide/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210603T040540Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "690e20b7-7b02-487c-b294-57f14a64755a"
      Hint: Title
      Value: $name
