---
ID: "2dc5f6d0-84c6-4c1e-b6cc-23fc44e79c2d"
Parent: "19d4b8e2-e034-48fa-94c0-f0942cacf2b1"
Template: "2b8ef99b-6377-437c-b3d9-f70cc8b4dbd8"
Path: /sitecore/content/Builderz/Home/Project
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 600
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{68C325C9-0878-4BCF-91E4-563F158D1363}"
          p:after="*[1=2]"
          s:ds="{F6724602-36A8-466B-A485-FA9B4649AEFB}"
          s:id="{6B5B0FE6-5C85-4487-BA7E-F8C2ECC186A8}"
          s:par=""
          s:ph="main" />
      </d>
    </r>
Languages:
- Language: en
  Fields:
  - ID: "502dcb42-c094-4490-b94e-4d7a382ddb61"
    Hint: Title
    Value: Project
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210604T063712Z
    - ID: "5250cc4e-93da-4311-b80a-331470a1cf08"
      Hint: NavigationTitle
      Value: Project
