---
ID: "0a942bac-16bc-42bb-b990-ca3340174ea6"
Parent: "19d4b8e2-e034-48fa-94c0-f0942cacf2b1"
Template: "2b8ef99b-6377-437c-b3d9-f70cc8b4dbd8"
Path: /sitecore/content/Builderz/Home/Service
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 800
Languages:
- Language: en
  Fields:
  - ID: "502dcb42-c094-4490-b94e-4d7a382ddb61"
    Hint: Title
    Value: Service
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210604T063648Z
    - ID: "5250cc4e-93da-4311-b80a-331470a1cf08"
      Hint: NavigationTitle
      Value: Service
